name: "Verify api endpoints documented"
inputs:
  diff_file_path:
    description: "Diff file"
    required: true
    type: string
  
runs:
  using: 'composite'
  steps:
      - name: Setup jruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.3.0.0'
      - name: Run verification script
        id: verification_script
        run: |
          ls -l
          message=$(jruby $GITHUB_ACTION_PATH/verify_sinatra_endpoints_documented.rb)
          echo $message
        env:
          DIFF_FILE_PATH: ${{ inputs.diff_file_path }}
          GITHUB_ACTION_PATH: ${{ github.action_path }}
        shell: bash


        # Challange 1: Creating a diff file restricting it to only lib/*_app pattern file changes, Do not need all files
        # Chalange  2: Get diff file generated in previous step and pass it to the next steps
        # Chalange  3: Having diff file path as an input but how to map url prefixes should 