name: "Check PR diff"
on:
  [pull_request]

jobs:
  verification:
    runs-on: ubuntu-latest
    name: PR Diff
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch only the last 2 commits
      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Show diff of changed files
        shell: bash
        run: |
          echo $(git diff -U0 origin/$BASE_BRANCH...HEAD -- *.md | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | grep -E '^\s*(get|post|put|delete|patch)\s+' | tr -d "'" | tr -d '"' | sed 's/^[ \t]*//;s/[ \t]*$//') > diff.txt
          cat diff.txt
        env:
          BASE_BRANCH: ${{ github.base_ref }}
      - name: Check if diff file still exists
        run: |
          ls -l
      - name: Setup jruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.3.0.0'
      - name: Run verification script
        id: verification_script
        run: |
          pwd
          message=$(jruby $GITHUB_ACTION_PATH/verify_sinatra_endpoints_documented.rb)
          echo $message
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}
        shell: bash
      